apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: module1.tanzu.vmware.com
  namespace: module1
spec:
  displayName: "module1"
  longDescription: ""
  shortDescription: ""
  providerName: VMware
  maintainers:
    - name: ""
  categories:
    - ""
