#@data/values
---
repositories:
  management:
    version: null
    sha256: latest
    name: my-repo
    domain: example.com
    registry: registry

    packageSpec:
      syncPeriod: 5m
      deploy:
        kappWaitTimeout: 5m
        kubeAPIQPS: 20
        kubeAPIBurst: 30

    packages:
      - name: my-integration
        displayName: my-integration
        #! Relative path to package bundle
        path: packages/my-integration
        domain: example.com
        version: latest
        #! Gets replaced with imgpkg sha256 at build, this should be name:version
        sha256: "my-integration-manager:latest"
